name: xedu
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  connectivity_plus: ^3.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.12
  flutter_spinkit: ^5.1.0
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  timeago: ^3.3.0

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  mocktail: ^0.2.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
